about_us/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('', views.about_us, name='about_us'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
 
urlpatterns = [
    path('film-list', views.film_list, name='film_list'),
    path('serial-list', views.serial_list, name='serial_list'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('films/', include(('films.urls', 'films'), namespace='film')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace="account")), 
    path('play/', include(('player.urls', 'player'), namespace='player')),
    path('marks/', include(('marks.urls', 'marks'), namespace='mark')),
    path('serial/', include(('serials.urls', 'serials'), namespace='serial')),
    path('list/', include(('movieList.urls', 'movieList'), namespace='list')),
    path('search/', include(('search.urls', 'search'), namespace='search')),
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
    path('aboutus/', include(('about_us.urls', 'about_us'), namespace="about_us")), 
    path('manual/', include(('manual.urls', 'manual'), namespace="manual")), 
    path('api/', include(('api.urls', 'api'), namespace="api")), 
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
 
urlpatterns = [
    path('', views.home, name='home'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('', views.manual, name='manual'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
 
urlpatterns = [
    path('', views.search, name='search'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
 {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap-theme.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/css/all.css' %}">
  <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
  <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pangolin|Oswald">
  <script src="{% static '/js/jq.min.js' %}"></script>
  <script src="{% static '/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/js/main.js' %}"></script>
  {% block extrahead %}
  {% endblock extrahead %}
<html>
<head>
  <meta name="google-site-verification" content="jAgeAx1orHB0pUSxyEaNjZcZPVjXVdLsySd3YDLYUVA" />	
  <meta name="yandex-verification" content="72c6d224abc0c4e6" />
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block head %}
  <title>OK Online Cinema 33</title>
  {% endblock %}
</head>
<body>
	<nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target="#bs_navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-family: 'Pangolin', sans-serif;">OK ONLINECINEMA</a>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="bs_navbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home:home' %}" style="font-family: 'Oswald', sans-serif;"><i class="fas fa-home"></i> Главная</a></li>
                <li class="dropdown">
                    <!--class="dropdown-toggle" data-toggle="dropdown"-->
                    <a href="{% url 'list:dateMovieList' %}" style="font-family: 'Oswald', sans-serif;"><i class="fas fa-film"></i> Фильмы</a>
                 <!--   <ul class="dropdown-menu">
                        <li><a>Мультфильмы</a></li><b class="caret"></b>
                        <li><a>Семейное</a></li>
                        <li><a>Приключения</a></li>
                    </ul>-->
                </li>
                <li><a style="font-family: 'Oswald', sans-serif;" href="{% url 'about_us:about_us' %}">О нас</a></li>
            </ul>
            <form class="navbar-form navbar-right" action="{% url 'search:search' %}" method="GET">
                <div class="form-group">
                    <input name="request" class="form-inline" type="text" placeholder="Поиск">
                    <button type="submit" class="btn btn-default btn-sm" style="font-family: 'Oswald', sans-serif;"><i class="fas fa-search"></i> Найти</button>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'account:profile' user.id %}" style="font-family: 'Oswald', sans-serif;"><i class="fas fa-user-circle"></i> Здравствуйте, {{ user.username }}!</a></li>
                    <li><a href="{% url 'logout' %}" style="font-family: 'Oswald', sans-serif;"><i class="fas fa-sign-out-alt"></i> Выйти</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}" style="font-family: 'Oswald', sans-serif;">Войти <i class="fas fa-sign-in-alt"></i></a></li>
                    <li><a href="{% url 'manual:manual' %}" style="font-family: 'Oswald', sans-serif;">Зарегистрироваться</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
  	{% block body %}
  	{% endblock %}
  	<footer class="footer-classic" style="font-family: 'Oswald', sans-serif;">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h5>Контакты:</h5>
                    <dl class="contact-list">
                        <dt>Адрес:</dt>
                        <dd>пр. Фрунзе 37, Ярославль, Россия</dd>
                    </dl>
                    <dl class="contact-list">
                        <dt>email:</dt>
                        <dd><a href="mailto:#">okcinema33@gmail.com</a></dd>
                    </dl>
                </div>
                <div class="col-md-4 col-xl-3">
                    <h5>Ссылки</h5>
                    <ul class="nav-list">
                        <li><a href="{% url 'about_us:about_us' %}">О нас</a></li>
                        <li><a href="{% url 'list:dateMovieList' %}">Фильмы</a></li>
                    </ul>
                </div>
            </div>
            <div class="no-gutters social-container">
                <div class="col"><a class="social-inner" href="#"><span><i class="fab fa-facebook-square"></i> Facebook</span></a></div>
                <div class="col"><a class="social-inner" href="https://www.instagram.com/okcinema33/"><span><i class="fab fa-instagram-square"></i> Instagram</span></a></div>
                <div class="col"><a class="social-inner" href="#"><span><i class="fab fa-twitter-square"></i> Twitter</span></a></div>
                <div class="col"><a class="social-inner" href="okcinema33@gmail.com"><span><i class="fab fa-google-plus-square"></i> Google</span></a></div>
            </div>
        </div>
    </footer>
    <script>
        if ($(document).height() <= $(window).height())
            $("footer.footer-classic").addClass("navbar-fixed-bottom");
    </script>
</body>
</html>