api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
 
urlpatterns = [
    path('film-list', views.film_list, name='film_list'),
    path('serial-list', views.serial_list, name='serial_list'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('films/', include(('films.urls', 'films'), namespace='film')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace="account")), 
    path('play/', include(('player.urls', 'player'), namespace='player')),
    path('marks/', include(('marks.urls', 'marks'), namespace='mark')),
    path('serial/', include(('serials.urls', 'serials'), namespace='serial')),
    path('list/', include(('movieList.urls', 'movieList'), namespace='list')),
    path('search/', include(('search.urls', 'search'), namespace='search')),
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
    path('aboutus/', include(('about_us.urls', 'about_us'), namespace="about_us")), 
    path('manual/', include(('manual.urls', 'manual'), namespace="manual")), 
    path('api/', include(('api.urls', 'api'), namespace="api")), 
]

films/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
 
urlpatterns = [
    path('<int:id>/', views.single, name='film'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
 
urlpatterns = [
    path('', views.home, name='home'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('', views.manual, name='manual'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
 
urlpatterns = [
    path('<int:id>/ball/', views.ball, name='ball'),
    path('inf/', views.info, name="info"),
    path('<int:id>/recension/', views.recension, name='recension'),
    path('<int:id>/recension/list/', views.recension_list, name='recension_list'),
    path('recension/<int:id>/', views.single_recension, name='single_recension'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

player/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
 
urlpatterns = [
    path('<int:id>/<int:season>/<int:number>', views.player, name='player'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serials/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('<int:id>/', views.serial, name='serial'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about_us/views.py
from django.shortcuts import render

def about_us(request):
    return render(request, 'partial/aboutus.html')

home/views.py
from django.shortcuts import render, get_object_or_404, Http404
from films.models import Film
from serials.models import Serial
from itertools import chain

def home(request):
    filmList = Film.objects.order_by('-date')
    list1 = list(chain(filmList))
    while len(list1) > 3:
        del list1[len(list1)-1]
    serialList = Serial.objects.order_by('-date')
    list2 = list(chain(serialList))
    while len(list2) > 3:
        del list2[len(list2)-1]
    context = {
        "filmList": list1,
        "sList": list2,
        "title": "Главная страница кинотеатра",
    }
    return render(request, "partial/home.html", context)

manual/views.py
from django.shortcuts import render

def manual(request):
    return render(request, 'partial/manual.html')

player/views.py
from django.shortcuts import render, get_object_or_404, Http404
from films.models import Film
from serials.models import Seriya
def player(request, id=None, season=None, number=None):
    try:
        video = get_object_or_404(Film, id=id)
    except Http404:
        video = get_object_or_404(Seriya, season=season, number=number) 
    context={
        "v":video,
    }
    return render(request, "partial/player.html", context)

templates/partial/aboutus.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h3 style="font-family: 'Pangolin', sans-serif;">Аккаунты разработчиков:</h3>
    <p style="font-family: 'Oswald', sans-serif;">ВКонтакте: <a href="https://vk.com/okcinema33">https://vk.com/okcinema33</a><br>
    Instagram: <a href="https://www.instagram.com/okcinema33/">https://www.instagram.com/okcinema33/</a><br>
    Email: <a href="okcinema@gmail.com">okcinema33@gmail.com</a></p>
</div>
{% endblock %}

templates/partial/createRecension.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <form class="form" action="{% url 'mark:recension' film.id %}" method="post">
      {% csrf_token %}
      {% if rForm.error_dict %}
        <p class="error">Пожалуйста исправьте нижеприведённые ошибки.</p>
      {% endif %}

      {% if rForm.title.errors %}
        {{ rForm.title.html_error_list }}
      {% endif %}
      <div class="form-group">
      <label for="id_title">Заголовок рецензии:</label> <br> {{ rForm.title }}  
      </div>
      {% if rForm.text.errors %}
          {{ rForm.text.html_error_list }}
      {% endif %}
      <div class="form-group">
      <label for="id_text">Текст рецензии:</label> <br> {{ rForm.text }}
      </div>
      <input class="btn btn-default" id="submit" type="submit" value="Отправить">
      {{rForm.media}}
  </form>
</div>
{% endblock body %}

templates/partial/home.html
{% extends 'base.html' %}
{% block head %}
<title>{{ title }}</title>
{% endblock %}
{% block body %}
    <header class="header"></header>
	<br>
	<div class="container">
    	<h3 style="font-family: 'Pangolin', sans-serif;"><strong>Новинки:</strong></h3>
		<br>
		<h4 style="font-family: 'Pangolin', sans-serif;">Фильмы:</h4>
    	<div class="row blog">
			{% for obj in filmList %}
        	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
				<div class="card">
					<div class="card-img">
						<img align="center" src="{{obj.poster.url}}" class="img-fluid">
					</div>
					<div class="card-body">
						<h4 style="font-family: 'Oswald', sans-serif;">{{ obj.title }}</h4>
						<p class="card-text" style="font-family: 'Oswald', sans-serif;">
							{{ obj.description|truncatechars:70 }}
						</p>
					</div>
					<div class="card-footer" style="font-family: 'Oswald', sans-serif;">
						<a href="{% url 'film:film' obj.id%}" class="card-link">Смотреть</a>
					</div>
				</div>
			</div>
			{% endfor %}
			</div>
			<br>
			<h4 style="font-family: 'Pangolin', sans-serif;">Сериалы:</h4>
			<div class="row blog">
			{% for obj in sList %}
        	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
				<div class="card">
					<div class="card-img">
						<img align="center" src="{{obj.poster.url}}" class="img-fluid">
					</div>
					<div class="card-body">
						<h4 style="font-family: 'Oswald', sans-serif;">{{ obj.title }}</h4>
						<p class="card-text" style="font-family: 'Oswald', sans-serif;">
							{{ obj.description|truncatechars:70 }}
						</p>
					</div>
					<div class="card-footer" style="font-family: 'Oswald', sans-serif;">
						<a href="{% url 'serial:serial' obj.id%}" class="card-link">Смотреть</a>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
    </div>
{% endblock %}

templates/partial/information.html
{% extends 'base.html' %}
 
{% block body %}
    <h1 style="font-family: 'Pangolin', sans-serif;">{{title}}</h1>
    <p style="font-family: 'Oswald', sans-serif;">{{text}}</p>
{% endblock %}

templates/partial/list.html
{% extends 'base.html' %}
{% block body %}
	<div class="container">
    	<h3 style="font-family: 'Pangolin', sans-serif;">Список:</h3>
    	<div style="font-family: 'Oswald', sans-serif;" class="row blog">
			{% for obj in movieList %}
        	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
				<div class="card">
					<div class="card-img">
						<img align="center" src="{{obj.poster.url}}" class="img-fluid">
					</div>
					<div class="card-body">
						<h4 style="font-family: 'Oswald', sans-serif;">{{ obj.title }}</h4>
						<p class="card-text">
							{{ obj.description|truncatechars:70 }}
						</p>
					</div>
					<div class="card-footer">
						{% if obj.get_class_name == 'Film'%}
						<a href="{% url 'film:film' obj.id%}" class="card-link">Смотреть</a>
						{% else %}
						<a href="{% url 'serial:serial' obj.id%}" class="card-link">Смотреть</a>
						{% endif %}
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
    </div>
{% endblock %}

templates/partial/manual.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h2 style="font-family: 'Pangolin', sans-serif;">Что такое OK Online Cinema 33?</h1>
    <p style="font-family: 'Oswald', sans-serif; color:#FFF;">Это инновационный интернет-кинотеатр, 
    позволяющий в разы ускорить подготовку к просмотру. Каким образом? 
    Теперь Вы можите выбрать фильм на одном устройстве и сразу же приступить к просмотру 
    на другом.</p>
    <h2 style="font-family: 'Pangolin', sans-serif;">Как этим пользоваться?</h2>
    <p style="font-family: 'Oswald', sans-serif; color:#FFF;">Вам нужно перейти в раздел фильмы, 
    выбрать тот, который хотите посмотреть, нажать на него. 
    Вы попадёте на страницу, на которой вам будут доступнен просмотр в браузере и просмотр на Android-устройстве. 
    Для второго будет необходимо установить на ваш девайс приложение, которое Вы можите скачать по ссылке: 'здесь будет ссылка' </p>
    <a class="btn btn-default" href="{% url 'accounts:signup' %}">Начать</a>
</div>
{% endblock body %}

templates/partial/player.html
{% extends 'base.html' %}

{% block extrahead %}
    {% load static %}
    <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" /><link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />
    <script src="{% static '/js/mediaelement-and-player.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/mediaelementplayer.min.css' %}" />
    <style>
        .mejs__overlay-button {
	        background-image: url("{% static 'img/mejs-controls.svg'%}");
        }
        .mejs__overlay-loading-bg-img {
	        background-image: url("{% static 'img/mejs-controls.svg'%}");
        }
        .mejs__button > button {
	        background-image: url("{% static 'img/mejs-controls.svg'%}");
        }
</style>
{% endblock %} 

{% block body %}
    {% if user.is_authenticated %}
    <video style="border: 0; width: 100%; height: 100%;" src="{{ v.video }}"></video>
    <script>
        $(document).ready(function() {
            $('video').mediaelementplayer({
                alwaysShowControls: false,
                videoVolume: 'horizontal',
                features: ['playpause', 'progress', 'volume', 'fullscreen']
            })
        });
    </script>
    {% endif %}
{% endblock %}

templates/partial/recension_list.html
{% extends 'base.html' %}
{% block body %}
	<div class="container">
    	<h3 style="font-family: 'Pangolin', sans-serif;">Рецензии:</h3>
    	<div style="font-family: 'Oswald', sans-serif;" class="row blog">
			{% for obj in rList %}
        	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
				<div class="card">
					<div class="card-body">
						<h4>{{ obj.title }}</h4>
						<p class="card-text">
							{{ obj.text|truncatechars:70 }}
						</p>
					</div>
					<div class="card-footer">
						<a href="{% url 'marks:single_recension' obj.id%}">Читать далее</a>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
        <a style="font-family: 'Pangolin', sans-serif;" href="{% url 'mark:recension' film.id %}"><button class="btn btn-default">Оставить рецензию</button></a>
	</div>
	<script>
		$("p").
		contents().
		filter(function(i,el){   return el.nodeType === 3; }).
		each(function(i, el){ 
			var $el = $(el);
			var replaced = $el.text().replace(/"(.*?)"/g,'"$1"') 
			$el.replaceWith(replaced); 
		});
	</script>
{% endblock %}

templates/partial/single.html
{% extends 'base.html' %}
{% block head %}
    <title>{{ film.title }}</title>
{% endblock %}

{% block body %}
    {% load qr_code %}
    <div class="container">
        <h1 style="font-family: 'Pangolin', sans-serif;">{{ film.title }}</h1>
        <img class="poster" src="{{ film.poster.url }}">
        <p style="font-family: 'Oswald', sans-serif;">Жанры: {% for g in genres %} {{g.name}}{% endfor %}</p>
        <p style="font-family: 'Pangolin', sans-serif; color: #FFF;">{{ film.description }}</p>
        <h2 style="font-family: 'Pangolin', sans-serif;">Оценка на OK Online Cinema 33: <span style="color: #FFF;">{{ film.raiting }}</span></h2>
        {% if kp_exist %}
        <h2 style="font-family: 'Pangolin', sans-serif;">Оценка на КиноПоиск: <span style="color: #FFF;">{{ kp_rait }}</span></h2>
        {% endif %}
        {% if imdb_exist %}
        <h2 style="font-family: 'Pangolin', sans-serif;">Оценка на IMDB: <span style="color: #FFF;">{{ imdb_rait }}</span></h2>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'player:player' film.id 1 1 %}">
                <button class="btn btn-default" style="font-family: 'Oswald', sans-serif;">Просмотр</button>
            </a>
            <br>
            <br>
            <details>
                <summary style="font-family: 'Oswald', sans-serif;" class="btn btn-default">Смотреть на Android</summary>
                <h1></h1>
                <img src="{% qr_url_from_text film.video size=4 version=10 image_format='png' %}">
            </details>
            <br>
            {% if notIsMarked %}
                <p style="font-family: 'Oswald', sans-serif;">Посмотрели? Оцените:</p>
                <form style="font-family: 'Oswald', sans-serif;" class="form" action="{% url 'mark:ball' film.id %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <br>
                    <input class="btn btn-default" type="submit" value="OK">
                </form>
            {% endif %}
            <a style="font-family: 'Oswald', sans-serif;" href="{% url 'mark:recension_list' film.id %}">Рецензии</a>
        {% else %}
            <p style="font-family: 'Oswald', sans-serif;"><a href="{% url 'login' %}">Войдите</a>, чтобы посмотреть</p>
        {% endif %}
    </div>
    <br>
{% endblock %}

templates/partial/single_recension.html
{% extends 'base.html' %}
{% block body %}
	<div class="container">
        <h2 style="font-family: 'Pangolin', sans-serif;">{{ r.title }}</h2>
		<p style="font-family: 'Oswald', sans-serif;">{{ r.text}} </p>
	</div>
	<script>
		$("p").
		contents().
		filter(function(i,el){   return el.nodeType === 3; }).
		each(function(i, el){ 
			var $el = $(el);
			var replaced = $el.text().replace(/"(.*?)"/g,'"$1"') 
			$el.replaceWith(replaced); 
		});
	</script>
{% endblock %}

templates/partial/single_serial.html
{% extends 'base.html' %}
{% block head %}
<title>{{ s.title }}</title>
{% endblock %}
 
{% block body %}
    <div class="container">
        <h1>{{ s.title }}</h1>
        <img class="poster" src="{{s.poster.url}}">
        <p>{{s.description}}</p>
        <h2>Оценка на OK Online Cinema 33: {{s.raiting}}</h2>
        {% if kp_exist %}
        <h2 style="font-family: 'Pangolin', sans-serif;">Оценка на Kinopoisk: {{ kp_rait }}</h2>
        {% endif %}
        {% if imdb_exist %}
        <h2 style="font-family: 'Pangolin', sans-serif;">Оценка на IMDB: {{ imdb_rait }}</h2>
        {% endif %}
        {% if user.is_authenticated %}
        {% for ses in range %}
            <h3>Сезон {{ forloop.counter }}</h3>
                {% for ser in sers %}
                    {% if ser.season == forloop.parentloop.counter %}
                        <a href="{% url 'player:player' ser.id ser.season ser.number%}">{{ser.number}}.{{ser.title}}</a>
                    {% endif %}
                {% endfor %}
        {% endfor %}
        {% if notSerIsMarked %}
        <p>Посмотрели? Оцените:</p>
        <form class="form" action="{% url 'mark:ball' s.id %}" method="post">
            {% csrf_token %}
            {{form}}
            <br>
            <input class="btn btn-default" type="submit" value="OK">
        </form>
        {% endif %}
        <a href="{% url 'mark:recension_list' s.id %}">Рецензии</a>
        {% else %}
        <p><a href="{% url 'login' %}">Войдите</a>, чтобы посмотреть</p>
        {% endif %}
    </div>
    <br>
{% endblock %}